### PR TITLE
E2E-479 Ask when the appointment is

### PR DESCRIPTION
**Pull request by electrified**

### CODE REVIEW

**Comment by benilovj** [comment]
@electrified how does the time picker look and work? (can you post a video of a animated gif)

**Comment by electrified** [comment]
> @electrified how does the time picker look and work? (can you post a video of a animated gif)

Sure!

Peek 2021-05-13 15-10

**Comment by fofr** [comment]
Some questions about how this works:

- If I type `9am` rather than `9:00am` does that still trigger the autocomplete?
- Can I enter custom times, like 11:10am?
- I love that it works with 24hr times as well (we saw a user do this)

The spacing between the fields is a little tight, it should be more like this:
Screen Shot 2021-05-13 at 15 44 02

**Comment by electrified** [comment]
Hi @fofr,

Thanks for the review! I'll fix the spacing.

Both those scenarios work:

Peek 2021-05-13 15-55

**Review by axle-h — APPROVED** [review]

**Pull request merged**
